name: Fetch daily analytics
on:
  schedule:
    - cron: "0 2 * * *"
jobs:
  analytics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        # install dependencies for scraper script
        run: npm ci
        working-directory: ./sh/parse-analytics
      - name: Fetch analytics for yesterday
        # fetch analytics, filter for yesterday, convert to CSV, write to file
        run: |
          mkdir -p "./src/_data/analytics/"
          echo ${{secrets.ANALYTICS_URL }} | sed 's/./& /g'
          curl '${{ secrets.ANALYTICS_URL }}' -s | \
          node ./sh/parse-analytics > \
          "./src/_data/analytics/$(date -d yesterday +"%Y-%m-%d").csv"
      - name: Set up git config
        # commit as a made up bot user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        # if there are changes commit and push
        run: |
          git add .
          # only commit if there's a change
          git diff --quiet --staged || git commit -m "Analytics for $(date -d yesterday +"%Y-%m-%d")"
          git push origin main
